from PyQt5 import QtCore, QtGui, QtWidgets
from price import *


class Ui_GetCurrency(object):
    def setupUi(self, GetCurrency):
        GetCurrency.setObjectName("GetCurrency")
        GetCurrency.setEnabled(True)
        GetCurrency.resize(410, 340)
        GetCurrency.setMinimumSize(QtCore.QSize(410, 340))
        GetCurrency.setMaximumSize(QtCore.QSize(410, 340))
        self.centralwidget = QtWidgets.QWidget(GetCurrency)
        self.centralwidget.setObjectName("centralwidget")
        self.dollar = QtWidgets.QLabel(self.centralwidget)
        self.dollar.setGeometry(QtCore.QRect(270, 30, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.dollar.setFont(font)
        self.dollar.setObjectName("dollar")
        self.pound = QtWidgets.QLabel(self.centralwidget)
        self.pound.setGeometry(QtCore.QRect(270, 90, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pound.setFont(font)
        self.pound.setObjectName("pound")
        self.bitcoin = QtWidgets.QLabel(self.centralwidget)
        self.bitcoin.setGeometry(QtCore.QRect(250, 150, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bitcoin.setFont(font)
        self.bitcoin.setObjectName("bitcoin")
        self.dollar_price = QtWidgets.QLabel(self.centralwidget)
        self.dollar_price.setGeometry(QtCore.QRect(30, 30, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dollar_price.setFont(font)
        self.dollar_price.setObjectName("dollar_price")
        self.pound_price = QtWidgets.QLabel(self.centralwidget)
        self.pound_price.setGeometry(QtCore.QRect(30, 90, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pound_price.setFont(font)
        self.pound_price.setObjectName("pound_price")
        self.bitcoin_price = QtWidgets.QLabel(self.centralwidget)
        self.bitcoin_price.setGeometry(QtCore.QRect(30, 140, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bitcoin_price.setFont(font)
        self.bitcoin_price.setObjectName("bitcoin_price")
        self.update = QtWidgets.QPushButton(self.centralwidget)
        self.update.setEnabled(True)
        self.update.setGeometry(QtCore.QRect(30, 230, 351, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.update.setFont(font)
        self.update.setObjectName("update")
        GetCurrency.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GetCurrency)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 410, 26))
        self.menubar.setObjectName("menubar")
        GetCurrency.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GetCurrency)
        self.statusbar.setObjectName("statusbar")
        GetCurrency.setStatusBar(self.statusbar)

        self.retranslateUi(GetCurrency)
        self.update.clicked.connect(self.get_data)
        #GetCurrency.windowTitleChanged['QString'].connect(GetCurrency.update)
        QtCore.QMetaObject.connectSlotsByName(GetCurrency)

    def retranslateUi(self, GetCurrency):
        _translate = QtCore.QCoreApplication.translate
        GetCurrency.setWindowTitle(_translate("GetCurrency", "دریافت ارز"))
        self.dollar.setText(_translate("Dollar : ", "دلار : "))
        self.pound.setText(_translate("Pound : ", "پوند : "))
        self.bitcoin.setText(_translate("Bit Coin : ", "بیت کوین : "))
        self.dollar_price.setText(_translate(" - ", " -"))
        self.pound_price.setText(_translate(" - ", " -"))
        self.bitcoin_price.setText(_translate(" - ", " -"))
        self.update.setText(_translate("Update", "بروزرسانی"))
    
    def get_data(self):
        try:
            self.bitcoin_price.setText(bitCoin())
            self.bitcoin_price.adjustSize()
            self.dollar_price.setText(dollar())
            self.dollar_price.adjustSize()
            self.pound_price.setText(pound())
            self.pound_price.adjustSize()
        except:
            self.bitcoin_price.setText("اشکال در اتصال")
            self.bitcoin_price.adjustSize()
            self.dollar_price.setText("اشکال در اتصال")
            self.dollar_price.adjustSize()
            self.pound_price.setText("اشکال در اتصال")
            self.pound_price.adjustSize()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GetCurrency = QtWidgets.QMainWindow()
    ui = Ui_GetCurrency()
    ui.setupUi(GetCurrency)
    GetCurrency.show()
    sys.exit(app.exec_())
